account/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name= 'index'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='signup'),
    path('freelancer/', views.freelancer, name='freelancer'),
    path('client/', views.client, name='client'),
    path("logout", views.logout_request, name= "logout"),
    path("account", views.account, name= "account"),
]

client/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('addpost', views.AddPost, name= 'addpost'),
    path('allpost', views.allpost, name= 'allpost'),
    path('detail/<int:id>', views.postdetails, name= 'detail'),
    path('update/<int:id>', views.postupdate, name= 'update'),
    path('delete/<int:id>', views.postdelete, name= 'delete'),
]

freelancer/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings 
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('client.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    is_client = "Client"
    is_freelancer = "Freelancer"
    
    ROLE = [ (is_client, "Client"),(is_freelancer, "Freelancer"),]
    role = models.CharField(max_length=50,choices=ROLE,default="is_client", null=True )
    

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class LoginForm(forms.Form):
    username = forms.CharField(
        widget= forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    email = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    
    
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2' , 'first_name' , 'last_name' , 'role')

account/views.py
from django.shortcuts import render, redirect
from .forms import SignUpForm, LoginForm
from django.contrib.auth import login, authenticate , logout
from django.contrib import messages
from client.models import AddpostModel
# Create your views here.


def index(request):
    Allposts=AddpostModel.objects.all()
    return render(request, 'index.html' , {'Allposts' : Allposts})


def register(request):
    msg = None
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            msg = 'user created'
            return redirect('login')
        else:
            msg = 'form is not valid'
    else:
        form = SignUpForm()
    return render(request,'signup.html', {'form': form, 'msg': msg})


def login_view(request):
    form = LoginForm(request.POST or None)
    msg = None
    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user :
                login(request, user)
                return redirect('index')
            else:
                msg= 'invalid credentials'
        else:
            msg = 'error validating form'
    return render(request, 'login.html', {'form': form, 'msg': msg})



def freelancer(request):
    return render(request,'freelancer.html')


def client(request):
    return render(request,'client.html')
    
def logout_request(request):
	logout(request)
	# messages.info(request, "You have successfully logged out.") 
	return redirect("index")
	
def account(request):
    return render(request, 'account.html')

templates/account.html
{% extends 'base.html' %}

{% block content %}


<div class="index1-listing-slider-wrapper float_left">
               <div class="container">
                  <div class="slider-text text-center">
                     <h4>Hey {{ user.first_name  }} {{ user.last_name  }} </h4>
                  </div>
               </div>
            </div>


<div class="freelauncer-main-wrapper float_left ptb-100">
               <div class="container">
                  <div class="home1-section-heading1">
                     <h4>Profile</h4>
                  </div>
                  <div class="freelauncer-profile float_left">
                     <div class="profile-img">
                        <img src="https://freelancerbucket.blob.core.windows.net/images/profile5.png" alt="profie">
                     </div>
                     <div class="profile-text ps-rel">
                        <a href="freelancer-listing-left-sidebar.html"><h6>{{ user.first_name  }} {{ user.last_name  }}</h6></a>
                        <a href="freelancer-listing-left-sidebar.html"><span>{{ user.role  }} </span></a><br>
                        <a href="freelancer-listing-left-sidebar.html"><span>{{ user.email  }} </span></a>
                        
                        <div class="rating-sec">
                           
                           <div class="rating-btn">
                              <a class="btn1" href="{% url 'addpost' %}">Add Post</a>
                              <a href="{% url 'allpost' %}">View All Post</a>
                           </div>
                           
                        </div>
                     </div>
                  </div>
                  <!--  -->
               </div>
            </div>


{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Freelancers</title>
    <link rel="stylesheet"  href="css/animate.css" />
            <link rel="stylesheet" type="text/css" href="https://freelancerbucket.blob.core.windows.net/css/animate.min.css" />
            <link rel="stylesheet" type="text/css" href="https://freelancerbucket.blob.core.windows.net/css/bootstrap.min.css" />
            <link rel="stylesheet" type="text/css" href="https://freelancerbucket.blob.core.windows.net/css/fonts.css" />
            <link rel="stylesheet" type="text/css" href="https://freelancerbucket.blob.core.windows.net/css/font-awesome.css" />
           <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
            <link rel="stylesheet" type="text/css" href="https://freelancerbucket.blob.core.windows.net/css/magnific-popup.css" />
            <link rel="stylesheet" type="text/css" href="https://freelancerbucket.blob.core.windows.net/css/owl.carousel.min.css" />
            <link rel="stylesheet" type="text/css" href="https://freelancerbucket.blob.core.windows.net/css/owl.theme.default.min.css" />
            <link rel="stylesheet" type="text/css" href="https://freelancerbucket.blob.core.windows.net/css/style.css" />
            <link rel="stylesheet" type="text/css" href="https://freelancerbucket.blob.core.windows.net/css/responsive.css" />
  </head>
  <body>


    <header>
      
      <div class="main-header-wrapper1 inner-main-header float_left">
               


               <div class="sb-main-header1">
                  <div class="menu-items-wrapper menu-item-wrapper3 d-xl-block d-lg-block d-md-none d-sm-none d-none">
                     <div class="container custom-container">
                        <div class="row">
                           <div class="col-lg-8 col-md-6">
                    <div class="index1-logo">
                       <a href="#">
                       <img class="normal-logo" src="https://seeklogo.com/images/F/freelancer-com-logo-2B5CE1A961-seeklogo.com.png" style="width: 30%" alt="logo">
                          <img class="sticky-logo" src="https://seeklogo.com/images/F/freelancer-com-logo-2B5CE1A961-seeklogo.com.png" style="width: 30%" alt="logo">
                       </a>
                    </div>
                    <nav class="navbar navbar-expand-lg">
                                 <ul class="navbar-nav">
                                    
                                    
                                    
                                    
                                    <li class="nav-item">
                                       <a class="nav-link" href="{% url 'index' %}">Home</a>
                                    </li>
                                    {% if user.is_authenticated and user.role == "Client" %}
                                    <li class="nav-item">
                                       <a class="nav-link" href="{% url 'account' %}">Account</a>
                                    </li>
                                     {% endif %}
                                 </ul>
                              </nav>
                 </div>
                 <div class="col-lg-4 col-md-6">
                   <ul class="d-xl-flex d-lg-flex d-md-none d-sm-none d-none justify-content-end align-items-center social-media-icons">
                   <li class="dekstop-login-btn">
                    {% if user.is_authenticated %}
                      <a href="{% url 'logout' %}"> <i class="fa fa-user-o" aria-hidden="true"></i> Logout</a>
                     {% else %}
                     <a href="{% url 'login' %}"> <i class="fa fa-user-o" aria-hidden="true"></i> Login</a>
                     {% endif %}

                     {% if user.is_authenticated %}
                      
                  
                   {% else %}
                   <a href="{% url 'signup' %}">/ Sign Up</a>
                   {% endif %}
                                 
 </li>
                                 
                                 {% if user.is_authenticated and user.role == "Client" %}
                                 <li class="post-drop">
                                    <a class="post-btn" href="{% url 'addpost' %}"><span>Post Now </span> </a>
                                    
                                 </li>
                                 {% else %}
                                  <li class="post-drop">
                                    <a class="post-btn" href="{% url 'login' %}"><span>Post Now </span> </a>
                                    
                                 </li>
                                 {% endif %}


                              </ul>
                 </div>
                        </div>
                     </div>
                  </div>
                  <!-- responsive menu bar start -->
                  
                  
                  <!-- responsive menu End -->
               </div>
            </div>

    </header>


{%  block  content%}
    {{ request.path }}  
{{ request.get_full_path }}  
    {%  endblock%}

  <script src="js/jquery-3.6.0.min.js"></script>
            <script src="https://freelancerbucket.blob.core.windows.net/js1/bootstrap.min.js"></script>
            <script src="https://freelancerbucket.blob.core.windows.net/js1/wow.js"></script>
            <script src="https://freelancerbucket.blob.core.windows.net/js1/jquery.magnific-popup.js"></script>
            <script src="https://freelancerbucket.blob.core.windows.net/js1/owl.carousel.min.js"></script>
            <script src="https://freelancerbucket.blob.core.windows.net/js1/contact_form.js"></script>
            <script src="https://freelancerbucket.blob.core.windows.net/js1/custom.js"></script>
  </body>
</html>

templates/clientpost.html
{% extends 'base.html' %}


{% block content %}



<style>
  .inner-page-main-wrapper.float_left {
    background: #f3f5fc;
}
</style>
<div class="index1-listing-slider-wrapper float_left">
               <div class="container">
                  <div class="slider-text text-center">
                     <h4>Update Job</h4>
                  </div>
               </div>
            </div>


<div class="inner-page-main-wrapper float_left " style="margin-top: 0px;">
               <div class="container mt-5">
                  <div class="home1-section-heading1">
                     <h6>Post Job</h6>
                     <h4>New Job Offer</h4>
                     <p>Add a new job to your company's jobs list.</p>
                  </div>
                  <div class="pt-5">
                     {% include 'message.html' %}
                  </div>

                  <div class="post-project-main-wrapper float_left">
                     <div class="row">
                     
                        <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                           <div class="post-form-wrapper float_left">
                                 <form method="POST" class="post-form" enctype="multipart/form-data"> 
                                  {% csrf_token %}  
                                 <div class="form-group row">
                                    <div class="col-md-6 col-12">
                                       <label>Job title</label>
                                       <input type="text" required="required" placeholder="Title" name="post_title">
                                    </div>
                                    <div class="col-md-6 col-12">
                                       <label>Cost</label>
                                        <input type="text" required="required" placeholder="Bid Amount" name="bidamount" >
                                    </div>
                                 </div>  

                                 <div class="form-group row">
                                    <div class="col-md-6 col-12">
                                       <label>Tags</label>
                                        <input type="text" required="required" placeholder="Please add tag using common for example (HTML5 , CSS3)" name="tags" >
                                    </div>
                                    <div class="col-md-6 col-12">
                                       <label>Development Type</label>
                                         <select class="form-select" name="tech" aria-label="Default select example">
              <option selected>Please select Category</option>
              <option value="frontend">Frontend</option>
              <option value="backend">Backend</option>
              <option value="cloud">Cloud</option>
            </select>
                                    </div>
                                 </div>  


                                 <div class="form-group row">
                                    <div class="col-md-12 col-12">
                                       <label>Job description</label>
                                       <textarea rows="4" cols="50" placeholder="Describe your project here..." name="post_content" >{{posts.post_content}}</textarea>
                                    </div>
                                 </div>
                                 <input type="hidden" name="user_role" value="{{ current_user.role }}"/>
                                 <input type="hidden" name="user_id" value="{{ current_user.id }}"/>
                                  <input type="submit" class="custom-btn btn" value="Publich Job"/>
                              </form>
                              
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>



{% endblock %}

templates/index.html
{% extends 'base.html' %}


{% block content %}

<section>
  <div class="index1-slider-wrapper ps-rel">
            <div class="overlay-slider">
               <div class="container">
                  <div class="slider-caption">
                     <h2>Offering 25,000 Freelancer Job </h2>
                     <p>The most complete Freelancer portal software having over 70 million unique <br> visitors every day with verified.</p>
                  </div>
                  <div class="sldier-contact-form">
                     <ul>
                        <li>
                           <div class="text-field">
                              <input type="text" placeholder="Search Here"> 
                           </div>
                        </li>
                        <li> <div class="select-field"> 
                        <select>
                        <option selected="selected" value="">Select Category</option>
                        <option value="5-6">Art &amp; Craft</option>
                        <option value="7-9">Science</option>
                        <option value="10-13">Maths </option>
                        <option value="10-13">English </option>
                        </select> </div>
                        </li>
                        <li> 
                        <div class="select-field"> 
                        <select>
                        <option selected="selected" value="">Select Location</option>
                        <option value="5-6">Art &amp; Craft</option>
                        <option value="7-9">Science</option>
                        <option value="10-13">Maths </option>
                        <option value="10-13">English </option>
                        </select> 
                        </div>
                        </li>
                        <li class="btn-from">
                        <a href="javascript:;"><span>Search</span></a>
                        </li>
                     </ul>
                     <ul class="treding-list">
                     <li> Trending Keyword:</li>
                     <li> <a href="javascript:;">UI Designer,</a> </li>
                     <li> <a href="javascript:;">Developer,</a> </li>
                     <li> <a href="javascript:;">it Company,</a> </li>
                     <li> <a href="javascript:;">Design,</a> </li>
                     <li> <a href="javascript:;">Call Center</a> </li>
                     </ul>
                     </div>
                  </div>
               </div>
               <div class="container">
               </div>
            </div>

</section>

<section>
  
<div class="treding-job-wrapper float_left ptb-100">
               <div class="container">
                  <div class="home1-section-heading1">
                     <h6>New Trending Jobs</h6>
                     <h4>Most Popular &amp; Trending Jobs</h4>
                  </div>
                  <div class="tabFive custom-tab">
                     <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12">
                           <div role="tabpanel" class="tab-panel">
                              <!-- Nav tabs -->
                              
                              <!-- Tab panes -->
                              <div class="tab-content">
                                 <div class="tab-pane fade active show" id="contentFive-1">
                                    <div class="row">


    {% for Allposts in Allposts %}
       <div class="col-lg-3 col-md-6 col-sm-6 col-12">
          <div class="trending-main-box float_left">
             <div class="trending-upper-text ps-rel">
              
                <div class="icon-img">
                   <img src="https://freelancerbucket.blob.core.windows.net/images/drive4.png" alt="img">
                </div>
                <a href="jobs-details.html"><h5>{{Allposts.post_title}}</h5></a>
             </div>
             <div class="trending-lower-text">
                <span style="text-transform: capitalize;">{{Allposts.tech}}</span>
                <a href="javascript:;"> {{Allposts.bidamount}} </a>
                <p> <span></span> {{Allposts.tags}}</p>
                <a class="custom-btn" href="detail/{{Allposts.id}}"> <span>View</span> </a>
             </div>
          </div>
       </div>
       {% endfor %}
                                       
                                       
                                       
                                       
                                       
                                       
                                       
                                    </div>
                                 </div>
                                 
                                 
                                 
                              </div>
                           </div>
                           
                        </div>
                     </div>
                  </div>
               </div>
            </div>
</section>
   




{% endblock %}

templates/message.html
{% for message in messages %}
<style >
	.alert {
    height: 50px;
}
</style>
<div class="container-fluid p-0">
    
    
    
    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
 {{ message }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
</div>
{% endfor %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}


<style>
  
  .signin-wrapper {
    margin-top: 10%;
}
select#id_role {
    width: 100%;
    height: 50px;
    border: 1px solid #eaf2f7;
    border-radius: 30px;
    background: #eaf2f7;
    padding: 0px 45px;
}
</style>
<section>
  <div class="login_box_main_wrapper" id="login_height" style="height: 1200px;">
            <div class="container">
               
               <div class="signin-wrapper">
                  <div class="row">
                     <div class="col-lg-6 col-md-6 col-12">
                        <div class="left-side">
                           <h4>Register</h4>
                            <span class="mb-0 text-danger">
                {% if msg %}
                    {{ msg | safe }}
                {% else %}
                    Login page
                {% endif %}
              </span>
                           <form method="post">
                             {% csrf_token %}
                             <label class="ml-3" for="username">Username</label>
                              <div class="form-group field-icon row">
                                 
                                 <div class="col-md-12">
                                   {{ form.username }}
                                    <span><i class="fa fa-user" aria-hidden="true"></i></span>
                                 </div>
                              </div>
                            
                              <label class="ml-3" for="username">First name</label>
                              <div class="form-group field-icon row">
                                 <div class="col-md-12">
                          
                                    {{ form.first_name }}
                                    <span><i class="fa fa-user" aria-hidden="true"></i></span>
                                 </div>
                              </div>

                              <label class="ml-3"  for="username">Last name</label>
                              <div class="form-group field-icon row">
                                 <div class="col-md-12">
                                  
                                    {{ form.last_name }}
                                    <span><i class="fa fa-user" aria-hidden="true"></i></span>
                                 </div>
                              </div>

                              <label class="ml-3"  for="username">Email</label>
                              <div class="form-group field-icon row">
                                 <div class="col-md-12">
                                    {{ form.email}}
                                    <span><i class="fa fa-unlock-alt" aria-hidden="true"></i></span>
                                 </div>
                              </div>

                               <label class="ml-3" for="username">Password</label>
                              <div class="form-group field-icon row">
                                 <div class="col-md-12">
                                     {{ form.password1 }}
                                    <span><i class="fa fa-unlock-alt" aria-hidden="true"></i></span>
                                 </div>
                              </div>

                              <label class="ml-3" for="username"> Confrom Password</label>
                              <div class="form-group field-icon row">
                                 <div class="col-md-12">
                                
                                     {{ form.password2 }}
                                    <span><i class="fa fa-unlock-alt" aria-hidden="true"></i></span>
                                 </div>
                              </div>

                              <label for="username">Select Role</label>
                              <div class="form-group field-icon row">
                                 
                                 <div class="col-md-12">
                                  
                                     {{ form.role }}
                                    <span><i class="fa fa-unlock-alt" aria-hidden="true"></i></span>
                                 </div>
                              </div>
                              
                               <span class="text-error">{{ form.errors }}</span>
                            
                              <div class="login-btn-sec">
                                <input type="submit"  value="Sign up" class="sub-btn">
                                 
                            
                              </div>
                           </form>
                       </div>
                     </div>
                     <div class="col-lg-6 col-md-6 col-12">
                        <div class="login-img">
                           <img src="https://freelancerbucket.blob.core.windows.net/images/login-side.png" alt="img">
                        </div>
                     </div>
                  </div>
               </div>
            </div>
          </div>

</section>




 <div class="content d-none">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-6 contents">
          <div class="row justify-content-center">
            <div class="col-md-12">
              <div class="form-block">
                  <div class="mb-4">
                      <h1>User Registration page</h1>
                </div>
                  <span class="mb-0 text-muted">
                {% if msg %}
                    {{ msg | safe }}
                {% else %}
                    Login page
                {% endif %}
              </span>
                <form  method="post">
                    {% csrf_token %}
                  <div class="form-group first">
                    <label for="username">Username</label>
                      {{ form.username }}
                  </div>
                  
                  <div class="form-group first">
                    <label for="username">First name</label>
                      {{ form.first_name }}
                  </div>
                  
                  
                  <div class="form-group first">
                    <label for="username">Last Name</label>
                      {{ form.last_name }}
                  </div>
                  <div class="form-group first">
                    <label for="email">Email</label>
                      {{ form.email}}
                  </div>
                  <div class="form-group last mb-4">
                    <label for="password">Password</label>
                      {{ form.password1 }}
                  </div>
                  <div class="form-group last mb-4">
                    <label for="password">confirm Password</label>
                      {{ form.password2 }}
                  </div>
                  <div class="d-flex mb-5 align-items-center">
                    <label class="control control--checkbox mb-0"><span class="caption">Freelancer</span>
                       
                      <div class="control__indicator"></div>
                    </label>
                  </div>
                  <div class="d-flex mb-5 align-items-center">
                    <label class="control control--checkbox mb-0"><span class="caption">Client</span>
                    {{ form.role }}
                      <div class="control__indicator"></div>
                    </label>
                  </div>
                   
                  <input type="submit"  value="Register" class="btn btn-pill text-white btn-block btn-primary">
                </form>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>

    

{% endblock %}